[project]
name = "wow-launcher-remember-password"
version = "1.0.0"
requires-python = ">=3.12, <3.14"
dependencies = [
    "keyring>=25.0",
    "numpy>=2.0",
    "opencv-python-headless>=4.13.0.92",
    "pillow>=12.2.0",
    'pyautogui',
    'pyotp',
]

[dependency-groups]
dev = [
    "pyinstaller>=6.20.0",
]
